export enum IconIdentifier {
  Bin = "bin",
  ChevronSmallLeft = "chevron-small-left",
  ChevronSmallRight = "chevron-small-right",
  Circle = "circle",
  Close = "close",
  Earth = "earth",
  Eye = "eye",
  EyeCross = "eye-cross",
  Freehand = "freehand",
  GoogleColor = "google-color",
  Line = "line",
  Logout = "log-out",
  MeatBallMenu = "meat-ball-menu",
  Plus = "plus",
  PointMarker = "point-marker",
  Polygon = "polygon",
  Rectangle = "rectangle",
  Satellite = "satellite",
  Search = "search",
  Select = "select",
  Tick = "tick",
}
