name: Lint Workflow

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - run: npm ci

      # Run linter
      - name: Run ESLint
        run: npm run lint
